version: '3.8'

services:
  ##### R2-11 #####
  navigation-build-11:
    build: .
    image: &IMG_NAME tu123/navigation2-humble:navigation2-humble
    container_name: &CONTAINER_NAME navigation2
    command: &CMD_BUILD /bin/bash -c "cd /home/user/Eurobot-2025-Navigation2-ws && colcon build"  # TODO: Check for working directories
    tty: true
    network_mode: host
    ipc: host
    privileged: true
    deploy: &DEPLOY_SETTING
      resources:
        limits:
          cpus: '2'

    # mount our navigation code
    volumes: &VOLUMES
      - /home/navigation/Eurobot-2025-machine-ws/:/home/user/Eurobot-2025-Navigation2-ws # TODO: Check for working directories
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $HOME/.Xauthority:/home/user/.Xauthority 
      - /dev:/dev

    working_dir: &WORKING_DIR
      /home/user/Eurobot-2025-Navigation2-ws  # TODO: Check for working directories

    environment: &ENV_11
      - DISPLAY=${DISPLAY}  # Set display environment variable
      - XAUTHORITY=/home/user/.Xauthority   # Set Xauthority path
      - ROS_HOSTNAME=dit-2025-11.local
      - ROS_DOMAIN_ID=25
    

  navigation-develop-11:
    build: .
    image: *IMG_NAME 
    container_name: *CONTAINER_NAME
    command: &CMD_DEVELOP /bin/bash
    tty: true
    network_mode: host
    ipc: host
    privileged: true
    deploy: *DEPLOY_SETTING

    # mount our navigation code
    volumes: *VOLUMES

    working_dir: *WORKING_DIR

    environment: *ENV_11
    

  navigation-run-11:
    build: .
    image: *IMG_NAME 
    container_name: *CONTAINER_NAME
    command: &CMD_RUN /bin/bash -c "cd /home/user/Eurobot-2025-Navigation2-ws && source install/local_setup.bash && ros2 launch navigation2_run real_launch.py"
    tty: true
    network_mode: host
    ipc: host
    privileged: true
    deploy: *DEPLOY_SETTING

    # mount our navigation code
    volumes: *VOLUMES

    working_dir: *WORKING_DIR

    environment: *ENV_11
    


  ##### R2-12 #####
  navigation-build-12:
    build: .
    image: *IMG_NAME
    container_name: *CONTAINER_NAME 
    command: *CMD_BUILD 
    tty: true
    network_mode: host
    ipc: host
    privileged: true
    deploy: *DEPLOY_SETTING

    # mount our navigation code
    volumes: *VOLUMES

    working_dir: *WORKING_DIR

    environment: &ENV_12
      - DISPLAY=${DISPLAY}  # Set display environment variable
      - XAUTHORITY=/home/user/.Xauthority   # Set Xauthority path
      - ROS_HOSTNAME=dit-2025-12.local
      - ROS_DOMAIN_ID=12
    

  navigation-develop-12:
    build: .
    image: *IMG_NAME 
    container_name: *CONTAINER_NAME
    command: *CMD_DEVELOP 
    tty: true
    network_mode: host
    ipc: host
    privileged: true
    deploy: *DEPLOY_SETTING

    # mount our navigation code
    volumes: *VOLUMES

    working_dir: *WORKING_DIR

    environment: *ENV_12
    

  navigation-run-12:
    build: .
    image: *IMG_NAME 
    container_name: *CONTAINER_NAME
    command: *CMD_RUN 
    tty: true
    network_mode: host
    ipc: host
    privileged: true
    deploy: *DEPLOY_SETTING

    # mount our navigation code
    volumes: *VOLUMES

    working_dir: *WORKING_DIR

    environment: *ENV_12



  ##### local #####
  # navigation-rviz-11:
  #   build: .
  #   image: *IMG_NAME
  #   container_name: *CONTAINER_NAME
  #   command: /bin/bash -c "cd /home/user/Eurobot-2025-Navigation2-ws && source install/local_setup.bash && ros2 launch navigation2_run rviz_launch.py" 
  #   tty: true 
  #   network_mode: host
  #   ipc: host
  #   privileged: True
  #   deploy: *DEPLOY_SETTING

  #   volumes: *VOLUMES_LOCAL
  #   environment:
  #     - DISPLAY=${DISPLAY}  # Set display environment variable
  #     - XAUTHORITY=/home/user/.Xauthority   # Set Xauthority path
  #     - &MY_IP ROS_HOSTNAME=192.168.50.109  # TODO: Check for IP Adress
  #     - ROS_DOMAIN_ID=12

  # navigation-rviz-12:
  #   build: .
  #   image: *IMG_NAME
  #   container_name: *CONTAINER_NAME
  #   command: /bin/bash -c "cd /home/user/Eurobot-2025-Navigation2-ws && source install/local_setup.bash && ros2 launch navigation2_run rviz_launch.py" 
  #   tty: true 
  #   network_mode: host
  #   ipc: host
  #   privileged: True
  #   deploy: *DEPLOY_SETTING

  #   volumes: *VOLUMES_LOCAL
  #   environment:
  #     - DISPLAY=${DISPLAY}  # Set display environment variable
  #     - XAUTHORITY=/home/user/.Xauthority   # Set Xauthority path
  #     - *MY_IP
  #     - ROS_DOAMIN_ID=12