version: '3.1'

services:
  navigation:
    build: .
    image: tu123/navigation2-humble:navigation2-humble
    container_name: navigation2
    command: /bin/bash
    tty: true
    network_mode: host
    ipc: host
    privileged: true

    # mount our navigation code
    volumes:
      # [IMPORTANT 2/3] Change the path to the navigation workspace on your host machine
      - ${HOME}/Eurobot-2025/Eurobot-2025-ws:/home/user/Eurobot-2025-Navigation2-ws
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $HOME/.Xauthority:/home/user/.Xauthority 

    # mount the serial device
    devices:
      - /dev:/dev  # Mount dev

    working_dir:
      /home/user/Eurobot-2025-Navigation2-ws

    environment:
      - DISPLAY=${DISPLAY}  # Set display environment variable
      - XAUTHORITY=/home/user/.Xauthority   # Set Xauthority path
    
    # [IMPORTANT 3/3] Change container hostname to that of the host machine's 
    # hostname: tars3017
 
