version: '3.8'

services:
  navigation-build-local:
    build: .
    image: &IMG_NAME tu123/navigation2-humble:navigation2-humble
    container_name: &CONTAINER_NAME navigation2
    command: /bin/bash -c "cd /home/user/Eurobot-2025-Navigation2-ws && colcon build"  # TODO: Check for working directories
    tty: true
    network_mode: host
    ipc: host
    privileged: true

    # mount our navigation code
    volumes: &VOLUMES_LOCAL
      - ${HOME}/Eurobot-2025/Eurobot-2025-ws:/home/user/Eurobot-2025-Navigation2-ws # TODO: Check for working directories
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $HOME/.Xauthority:/home/user/.Xauthority
      - /dev:/dev

    working_dir: &WORKING_DIR_LOCAL
      /home/user/Eurobot-2025-Navigation2-ws

    environment: &ENV_LOCAL
      - DISPLAY=${DISPLAY}  # Set display environment variable
      - XAUTHORITY=/home/user/.Xauthority   # Set Xauthority path\
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
      - ROS_DOMAIN_ID=25
  
  navigation-develop-local:
    build: .
    image: *IMG_NAME 
    container_name: *CONTAINER_NAME
    command: /bin/bash
    tty: true
    network_mode: host
    ipc: host
    privileged: true

    # mount our navigation code
    volumes: *VOLUMES_LOCAL

    working_dir: *WORKING_DIR_LOCAL

    environment: *ENV_LOCAL

  navigation-run-local:
    build: .
    image: *IMG_NAME
    container_name: *CONTAINER_NAME
    command: /bin/bash -c "cd /home/user/Eurobot-2025-Navigation2-ws" && source install/local_setup.bash && ros2 launch navigation2_run sim_launch.py
    tty: true
    network_mode: host
    ipc: host
    privileged: true

    # mount our navigation code
    volumes: *VOLUMES_LOCAL

    working_dir: *WORKING_DIR_LOCAL

    environment: *ENV_LOCAL
 
